FROM osixia/openldap

COPY ldif/bootstrap.ldif /container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif
COPY schema/date-of-birth.schema /container/service/slapd/assets/config/bootstrap/schema/date-of-birth.schema