version: '3.8'

services:
  mysql:
    image: mysql:8.0.22
    environment:
      MYSQL_ROOT_PASSWORD: "12345678"
      MYSQL_DATABASE: "massoterapiadb"
    ports:
      - 3306:3306
  openldap:
    build: .
    container_name: openldap
    command: --copy-service --loglevel debug
    environment:
      LDAP_TLS: "false"
      LDAP_DOMAIN: springframework.org
      LDAP_BASE_DN: dc=springframework,dc=org
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
    ports:
      - "389:389"
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8090:80"
    depends_on:
      - openldap
      
volumes:
  ldap_data:
  ldap_config:
  